# Generated by Django 4.2.1 on 2023-05-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('creationDate', models.DateTimeField()),
                ('isAvailable', models.BooleanField()),
                ('availableChangeDate', models.DateTimeField(blank=True, null=True)),
                ('valueChangeDate', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creationDate', models.DateTimeField()),
                ('beginning', models.IntegerField()),
                ('ending', models.IntegerField()),
                ('content', models.TextField()),
                ('dataStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.datastatus')),
                ('sectionStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.sectionstatus')),
                ('sectionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.sectiontype')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('creationDate', models.DateTimeField()),
                ('is_available', models.BooleanField()),
                ('availableChangeDate', models.DateTimeField()),
                ('valueChangeDate', models.DateTimeField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.user')),
            ],
        ),
    ]
