# Generated by Django 4.2.1 on 2023-05-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='is_available',
            new_name='isAvailable',
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.folder'),
        ),
    ]
