# Generated by Django 4.2.1 on 2023-05-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_alter_file_availablechangedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileToDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.file')),
            ],
        ),
    ]
