# Generated by Django 4.2.1 on 2023-05-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0013_alter_file_creationdate_alter_file_isavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
