# Generated by Django 4.2.1 on 2023-05-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0016_alter_file_isavailable_alter_file_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('beginning', models.IntegerField(blank=True, null=True)),
                ('ending', models.IntegerField(blank=True, null=True)),
                ('sectionType', models.TextField(choices=[('pro', 'Procedura'), ('com', 'Komentarz'), ('dir', 'Dyrektywa'), ('dec', 'Deklaracja'), ('inl', 'Wstawka assemblerowa')])),
                ('sectionStatus', models.TextField(choices=[('ok', 'Kompiluje się bez ostrzeżeń'), ('war', 'Kompiluje się z ostrzeżeniami'), ('fail', 'Nie kompiluje się')])),
                ('file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.file')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.user')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.section')),
            ],
        ),
        migrations.RemoveField(
            model_name='filesection',
            name='dataStatus',
        ),
        migrations.RemoveField(
            model_name='filesection',
            name='sectionStatus',
        ),
        migrations.RemoveField(
            model_name='filesection',
            name='sectionType',
        ),
        migrations.DeleteModel(
            name='DataStatus',
        ),
        migrations.DeleteModel(
            name='FileSection',
        ),
        migrations.DeleteModel(
            name='SectionStatus',
        ),
        migrations.DeleteModel(
            name='SectionType',
        ),
    ]
