# Generated by Django 4.2.1 on 2023-05-09 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0011_alter_folder_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='isAvailable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.user'),
        ),
    ]
