# Generated by Django 4.2.1 on 2023-05-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0012_alter_folder_isavailable_alter_folder_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='isAvailable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.user'),
        ),
    ]
