# Generated by Django 4.2.1 on 2023-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0018_alter_file_owner_alter_folder_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sectionStatus',
            field=models.TextField(blank=True, choices=[('ok', 'Kompiluje się bez ostrzeżeń'), ('war', 'Kompiluje się z ostrzeżeniami'), ('fail', 'Nie kompiluje się')], null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionType',
            field=models.TextField(blank=True, choices=[('pro', 'Procedura'), ('com', 'Komentarz'), ('dir', 'Dyrektywa'), ('dec', 'Deklaracja'), ('inl', 'Wstawka assemblerowa')], null=True),
        ),
    ]
